# point: X[m] Y[m] Z[m] YAW[rad] TIME[s]
/mission_supervisor:
  ros__parameters:
    posX_m:
    - 0.0
    - 0.0
    - 10.0
    - -10.0
    - 0.0
    - 0.0
    posY_m:
    - 0.0
    - 30.0
    - 30.0
    - -30.0
    - -30.0
    - 0.0
    posZ_m:
    - 5.0
    - 10.0
    - 15.0
    - 10.0
    - 7.0
    - 5.0
    yaw_rad:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    time_s:
    - 5.0
    - 5.0
    - 5.0
    - 10.0
    - 5.0
    - 5.0
    use_sim_time: false